language: zh
pipeline:
- name: "MitieNLP"
  model: "models/total_word_feature_extractor_zh.dat"
- name: "JiebaTokenizer"
  dictionary_path: "jieba_userdict"
- name: "MitieEntityExtractor"
- name: "EntitySynonymMapper"
- name: "RegexFeaturizer"
- name: "MitieFeaturizer"
- name: "SklearnIntentClassifier"